apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-only-private-dagt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-only-private-dagt
    app.kubernetes.io/part-of: mc-golang-nested
  name: devfile-sample-go-basic-dockerfile-only-private-dagt
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-only-private-dagt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-only-private-dagt
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-twvb-tenant/mc-golang-nested/devfile-sample-go-basic-dockerfile-only-private-dagt@sha256:6692f13f7160e8c48334559415fbee8e3142b1531862936306d7b92aa62b5ff9
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
